### ISSUE TITLE
error while making the benchmarks

### ISSUE THREAD

**Issue by anwesha94** [t-crest/patmos-benchmarks#3]
Hi,
I followed the README file and tried to make the benchmarks. However, it gives an error:

patmos-clang-3.4: error: no such file or directory: 'INCLUDES'
make[2]: *** [Debie1-e/code/patmos/clang/CMakeFiles/debie1-target.dir/target.c.bc] Error 1
make[1]: *** [Debie1-e/code/patmos/clang/CMakeFiles/debie1-target.dir/all] Error 2
make: *** [all] Error 2

I cound not find any directory named "INCLUDES" in any directory.
I have installed all the pre-requisites and included the paths as given in t-crest/patmos.
What am I missing here?
Thnaks,
Anwesha

**Comment by schoeberl** [comment]
Can you some more details on the error?

Martin
