### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by maroneze** [t-crest/patmos-benchmarks#5]
Hello,

I'd like to know what is the license associated with the code of the benchmarks. I know that some of them have their own specific license, but is there a general license for the repository code? Or an easy way to find out which license is associated to each benchmark? 

All I could find was a copyright disclaimer in the [T-Crest website](http://www.t-crest.org/page/results): 

> © 2012-2014 Copyright in all of the above documents and related software remains vested in the T-CREST Project Partners.

Does this apply to the `patmos-benchmarks` repository?

**Comment by schoeberl** [comment]
No, I don’t think so. The benchmarks have not been developed by the T-CREST project partners, but have been collected. So you need to look into the individual ones.

Cheers,
Martin

**Comment by maroneze** [comment]
Ok, thanks, I'll track down the licenses for the specific benchmarks I'm interested in.
